spring.application.name=rag_implementation
spring.datasource.url=jdbc:mysql://localhost:3306/rag_v1
spring.datasource.username=root
spring.datasource.password=Abhinav@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
spring.servlet.multipart.max-file-size=250MB
spring.servlet.multipart.max-request-size=250MB
pinecone.api-key=pcsk_2d5aPe_3BVjbykw2XsnoZHsSDnj8dHTp5VnuA35yaeZ3xFfxBCznFyKsBjXx1Xt7KCnY4U
pinecone.index-url=https://rag3359-72hmgaw.svc.aped-4627-b74a.pinecone.io